config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :phones do
        get 'order_number', on: :collection
        get 'get_list', on: :collection
      end
    end
  end

  resources :cities, only: [:index, :show]
  root 'home#index'
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :phones

  paginates_per 5
  max_paginates_per 100
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :city

  def as_json(options={})
    super(only: [:number])
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  respond_to :json
end

app/controllers/api/v1/phones_controller.rb
module Api
  module V1
    class PhonesController < ActionController::Base
      respond_to :json

      def get_list
        respond_with cities(params)
      end

      def order_number
        phone = Phone.find_by(number: params['number'])
        respond_with exist_phone?(phone)
      end

      private

      def exist_phone?(phone)
        if !phone.nil?
          { terms: terms, status: 'success', message: 'phone number exist' }
        else
          { terms: '', status: 'failure', message: 'phone number does not exist' }
        end
      end

      def exist_city?(params)
        if City.exists?(params['city_id'])
          @cities = City.find(params['city_id']).phones
        else
          { status: 'failure', error: 'This city ID does not exist' }
        end
      end

      def city_id_valid?(params)
        /^\d+$/ === params
      end

      def cities(params)
        if params[:city_id] && !city_id_valid?(params[:city_id])
          { status: 'failure', error: 'Bad request. Please provide a valid city ID' }
        elsif params[:city_id] && !params[:city_id].empty?
          exist_city?(params)
        end
      end

      def terms
        'Lorem ipsum dolor sit amet, consectetur adipiscing
        elit, sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad ...'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @country = Country.find_by(code: params['country'] ||= 'AR')
    @cities = Country.find_by(code: params['country'] ||= 'AR').cities.order(:name).page(params[:page] ||= 1)
  end

  def show
    @city = City.find(params['id'])
    @phones = @city.phones.limit(10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cities/_cities_list.haml
%h2
  %span.label.label-info= "Cities of #{@country.name}"
%hr
.row
  - @cities.each do |city|
    .col-md-12.panel.panel-default
      %h4.pull-left= link_to city.name, city_path(city)

= paginate @cities

app/views/cities/index.haml
#cities
  = render 'cities_list'

app/views/cities/show.haml
.row
  %h3.col-md-9= @city.name
  %h3.col-md-3.btn.btn-info.btn-md= link_to 'API get_list(direct link)', "/api/v1/phones/get_list?city_id=#{@city.id}", target: 'blank'
%hr
.row
  - @phones.each do |phone|
    - plus = [true, false].sample ? ' not existent ' : ''
    .col-md-8.panel.panel-default
      %h4.pull-left!= "#{phone.number} <span class='label label-danger'>#{plus}</span>"
    .col-md-4.panel.panel-default
      %h4.pull-= link_to("Order Number(Api Request #{plus})", "/api/v1/phones/order_number?number=#{phone.number}#{plus}", target: 'blank')

app/views/home/_form.haml
%form(action="#{cities_path}" method='GET' class='form-group' id='country-form')
  = hidden_field_tag :authenticity_token, form_authenticity_token
  %div.col-sm-10
    .bfh-selectbox.bfh-countries{'data-country': '', 'data-flags': 'true', 'data-name': 'country'}
      %input{type: 'hidden', value: ''}
      %a.bfh-selectbox-toggle{'data-toggle': 'bfh-selectbox', href: '#', role: 'button'}
        %span.bfh-selectbox-option.input-medium{'data-option': ''}
        %b.caret
      .bfh-selectbox-options
        %input.bfh-selectbox-filter{type: 'text'}/
        %div{role: 'listbox'}
          %ul{role: 'option'}
  %div.col-sm-10
    %button.btn.btn-default(type='submit') Send

app/views/home/cities.haml
#cities
  = render 'cities_list'

app/views/home/index.haml
= render 'form'

app/views/layouts/application.haml
!!!
%html
  %head
    %title Phones
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => '#'} Phones
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => '#'} Home
    .container
      = yield